# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kid.Kid')),
            ],
        ),
        migrations.CreateModel(
            name='KidUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('invalid_password_count', models.IntegerField()),
                ('last_login_date', models.DateTimeField()),
                ('kid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KidUser',
                'verbose_name_plural': 'KidUsers',
            },
        ),
        migrations.AddField(
            model_name='favorite',
            name='fav_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kid.KidUser'),
        ),
    ]
