# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kid', '0002_auto_20161111_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiduser',
            name='birthday',
            field=models.CharField(default=b'1900-01-01', max_length=10),
        ),
        migrations.AddField(
            model_name='kiduser',
            name='gender',
            field=models.CharField(default=b'M', max_length=1),
        ),
        migrations.AlterField(
            model_name='kiduser',
            name='invalid_password_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kiduser',
            name='last_login_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 16, 1, 5, 9, 113000)),
        ),
    ]
