# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kid', '0004_auto_20161119_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xec\x88\x98\xec\xa0\x95\xec\x9d\xbc'),
        ),
        migrations.AlterField(
            model_name='kiduser',
            name='address',
            field=models.CharField(max_length=200, verbose_name=b'\xec\xa3\xbc\xec\x86\x8c'),
        ),
        migrations.AlterField(
            model_name='kiduser',
            name='birthday',
            field=models.CharField(default=b'2000-01-01', max_length=10, verbose_name=b'\xec\x83\x9d\xeb\x85\x84\xec\x9b\x94\xec\x9d\xbc'),
        ),
        migrations.AlterField(
            model_name='kiduser',
            name='gender',
            field=models.CharField(choices=[(b'M', b'\xeb\x82\xa8\xec\x9e\x90'), (b'F', b'\xec\x97\xac\xec\x9e\x90')], default=b'M', max_length=1, verbose_name=b'\xec\x84\xb1\xeb\xb3\x84'),
        ),
        migrations.AlterField(
            model_name='kiduser',
            name='invalid_password_count',
            field=models.IntegerField(default=0, verbose_name=b'\xeb\xb9\x84\xeb\xb0\x80\xeb\xb2\x88\xed\x98\xb8 \xec\x8b\xa4\xed\x8c\xa8\xed\x9a\x9f\xec\x88\x98'),
        ),
        migrations.AlterField(
            model_name='kiduser',
            name='last_login_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xeb\xa7\x88\xec\xa7\x80\xeb\xa7\x89\xec\xa0\x91\xec\x86\x8d\xec\x9d\xbc'),
        ),
    ]
